#!/bin/sh
set -e
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ./caseParams.sh                                   # Case parameters
#------------------------------------------------------------------------------

controlDictBackup=""
restoreControlDict()
{
    if [ -n "$controlDictBackup" ] && [ -f "$controlDictBackup" ]; then
        cp "$controlDictBackup" system/controlDict
        rm -f "$controlDictBackup"
    fi
}

if [ -n "$END_TIME" ] || [ -n "$WRITE_INTERVAL" ]; then
    controlDictBackup=$(mktemp)
    cp system/controlDict "$controlDictBackup"
    trap restoreControlDict EXIT

    if [ -n "$END_TIME" ]; then
        foamDictionary system/controlDict -entry endTime -set "$END_TIME"
    fi

    if [ -n "$WRITE_INTERVAL" ]; then
        foamDictionary system/controlDict -entry writeInterval -set "$WRITE_INTERVAL"
    fi
fi

./Allclean
./prepareCase

runApplication cartesian2DMesh
runApplication extrudeMesh
./postMesh

restore0Dir
runApplication setAlphaField
rm -f 0/Pim.in

runApplication setPMLFields

rm -f "log.${SOLVER}"
runApplication decomposePar -force
runParallel "${SOLVER}"
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
