#!/bin/sh
set -e
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ./caseParams.sh                                   # Case parameters
#------------------------------------------------------------------------------

if [ "${RUN_MODE}" = "fullFig4Sweep" ] && [ "${TPF_INTERNAL_SWEEP_RUN:-0}" != "1" ]; then
    exec ./runHeightSweep.sh
fi

need_cmd()
{
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Error: required command '$1' not found in PATH" >&2
        exit 1
    fi
}

SOLVER=acousticHelmholtzFoam

need_cmd cartesian2DMesh
need_cmd extrudeMesh
need_cmd topoSet
need_cmd refineMesh

if [ -z "${NPROCS:-}" ]; then
    NPROCS="${RUN_NPROCS}"
fi
: "${NPROCS:=8}"

rm -f \
    log.cartesian2DMesh \
    log.extrudeMesh \
    log.topoSet.alphaInterface.* \
    log.refineMesh.alphaInterface.* \
    log.setAlphaField.alphaInterface.* \
    log.setAlphaField \
    log.setPMLFields \
    log.decomposePar \
    log.reconstructPar \
    "log.${SOLVER}"

./Allclean
./prepareCase

runApplication cartesian2DMesh
runApplication extrudeMesh
./postMesh

restore0Dir
need_cmd setAlphaField
runApplication setAlphaField

./refineAlphaInterface

rm -f 0/Pim.in

need_cmd setPMLFields
runApplication setPMLFields

need_cmd "${SOLVER}"
rm -f "log.${SOLVER}"
runApplication decomposePar -force
runParallel "${SOLVER}"
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
