#!/bin/bash

WITH_BEAR=$1

wmake $WITH_BEAR libso src/VoF
wmake $WITH_BEAR all src/boundaryConditions
wmake $WITH_BEAR all src/thermoDynamics

wmake $WITH_BEAR libso src/turbulence/VoFphaseCompressibleTurbulenceModels
wmake $WITH_BEAR libso src/phaseChange
wmake $WITH_BEAR libso src/surfaceForces

wmake $WITH_BEAR libso src/postProcessing

wmake $WITH_BEAR apps/setFieldfromTable
wmake $WITH_BEAR apps/initAlphaField

wmake $WITH_BEAR apps/benchmark/advectorVoF
wmake $WITH_BEAR apps/benchmark/reconstructInterface
wmake $WITH_BEAR apps/benchmark/testAreaFractions

wmake $WITH_BEAR solver/multiRegionPhaseChangeFlow
wmake $WITH_BEAR solver/interFlow
wmake $WITH_BEAR solver/compressibleInterFlow

