#!/bin/bash

withBear=$1

wmake $withBear libso src/VoF
wmake $withBear all src/boundaryConditions
wmake $withBear all src/thermoDynamics

wmake $withBear libso src/turbulence/VoFphaseCompressibleTurbulenceModels
wmake $withBear libso src/phaseChange
wmake $withBear libso src/surfaceForces

wmake $withBear libso src/postProcessing
wmake $withBear libso src/functionObjects/vofForcesFunctionObject
wmake $withBear libso src/triSurfaceImmersion

wmake apps/setFieldfromTable
wmake apps/initAlphaField
wmake apps/surfaceInitVolumeFraction

wmake $withBear apps/setFieldfromTable
wmake $withBear apps/initAlphaField
wmake $withBear apps/surfaceInitVolumeFraction

wmake $withBear apps/benchmark/advectorVoF
wmake $withBear apps/benchmark/reconstructInterface

wmake $withBear solver/multiRegionPhaseChangeFlow
wmake $withBear solver/interFlow
wmake $withBear solver/compressibleInterFlow

