#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf dynamicCode
rm -rf constant/coarseMesh
rm -f system/coarseMesh/decomposeParDict
rm -f *.dat
rm -f constant/*unrolled*
rm -f verification_*.csv verification_*.png
rm -f system/decomposeParDict.run
#------------------------------------------------------------------------------
