#!/bin/sh
set -e
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ./caseParams.sh                                   # Case parameters
#------------------------------------------------------------------------------

./Allclean
./prepareCase
restore0Dir
python3 generate_verification_probes.py >/dev/null

gmsh -0 constant/pistonRadiation.geo
runApplication gmshToFoam constant/pistonRadiation.msh
rm constant/pistonRadiation.msh

runApplication topoSet
runApplication createPatch -overwrite
runApplication changeDictionary -dict system/changeDictionaryDict
runApplication setPMLFields

runApplication decomposePar -force
runParallel "${SOLVER}"
runApplication reconstructPar -latestTime

python3 verify_piston_radiation.py
#------------------------------------------------------------------------------
