#!/bin/sh
set -eu

cd "${0%/*}" || exit 1
. ./caseParams.sh

calc()
{
    awk "BEGIN { printf \"%.12g\", $* }"
}

END_TIME=$(calc "$N_PERIODS / $DRIVE_F")
WRITE_INTERVAL=$(calc "1 / (10 * $DRIVE_F)")
PROBE_INTERVAL=$(calc "1 / ($DRIVE_F * $PROBE_SAMPLES_PER_PERIOD)")
CELL_SIZE=$(calc "$CG / $DRIVE_F / $MESH_CELLS_PER_LAMBDA")
HALF_ANGLE=$(calc "$WEDGE_ANGLE_DEG * atan2(0, -1) / 360")
OUTER_X=$(calc "$PML_RMAX * cos($HALF_ANGLE)")
OUTER_Z=$(calc "$PML_RMAX * sin($HALF_ANGLE)")
PISTON_X=$(calc "$PISTON_RADIUS * cos($HALF_ANGLE)")
PISTON_Z=$(calc "$PISTON_RADIUS * sin($HALF_ANGLE)")
N_AXIAL=$(awk -v extent="$PML_RMAX" -v h="$CELL_SIZE" '
    BEGIN { n = int(extent/h + 0.5) - 1; print (n > 0 ? n : 1) }
')
N_PISTON=$(awk -v extent="$PISTON_RADIUS" -v h="$CELL_SIZE" '
    BEGIN { n = int(extent/h + 0.5); print (n > 0 ? n : 1) }
')
N_OUTER_RADIAL=$(awk -v extent="$PML_RMAX" -v inner="$PISTON_RADIUS" -v h="$CELL_SIZE" '
    BEGIN { n = int((extent-inner)/h + 0.5); print (n > 0 ? n : 1) }
')

render()
{
    inFile="$1"
    outFile="$2"

    sed \
        -e "s|__SOLVER__|$SOLVER|g" \
        -e "s|__DRIVE_F__|$DRIVE_F|g" \
        -e "s|__PISTON_U__|$PISTON_U|g" \
        -e "s|__RHOL__|$RHOL|g" \
        -e "s|__RHOG__|$RHOG|g" \
        -e "s|__CG__|$CG|g" \
        -e "s|__CL__|$CL|g" \
        -e "s|__PISTON_RADIUS__|$PISTON_RADIUS|g" \
        -e "s|__PML_RMIN__|$PML_RMIN|g" \
        -e "s|__PML_RMAX__|$PML_RMAX|g" \
        -e "s|__MESH_CELLS_PER_LAMBDA__|$MESH_CELLS_PER_LAMBDA|g" \
        -e "s|__MESH_GR__|$MESH_GR|g" \
        -e "s|__WEDGE_ANGLE_DEG__|$WEDGE_ANGLE_DEG|g" \
        -e "s|__OUTER_X__|$OUTER_X|g" \
        -e "s|__OUTER_Z__|$OUTER_Z|g" \
        -e "s|__PISTON_X__|$PISTON_X|g" \
        -e "s|__PISTON_Z__|$PISTON_Z|g" \
        -e "s|__N_AXIAL__|$N_AXIAL|g" \
        -e "s|__N_PISTON__|$N_PISTON|g" \
        -e "s|__N_OUTER_RADIAL__|$N_OUTER_RADIAL|g" \
        -e "s|__END_TIME__|$END_TIME|g" \
        -e "s|__WRITE_INTERVAL__|$WRITE_INTERVAL|g" \
        -e "s|__PROBE_INTERVAL__|$PROBE_INTERVAL|g" \
        "$inFile" > "$outFile"
}

render constant/transportProperties.in constant/transportProperties
render system/blockMeshDict.in system/blockMeshDict
render system/controlDict.in system/controlDict
render templates/p.in 0.orig/p
