#!/usr/bin/env python3
"""Convergence of the L1 geometrical shape error, from the study's own CSV.

Part of the workflow rather than a side script, so the figure in the manuscript
has the same provenance as the tables: it is regenerated by `./run.sh` from
results/convergence.csv and nothing else.
"""

from __future__ import annotations

import argparse
import csv
import math
import os

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Font sizes are deliberately large: these figures are reduced to a single
# column in print, where the default matplotlib sizes become unreadable.
FS = 20
plt.rcParams.update({
    "font.size": FS,
    "axes.titlesize": FS + 2,
    "axes.labelsize": FS,
    "xtick.labelsize": FS - 2,
    "ytick.labelsize": FS - 2,
    "legend.fontsize": FS - 3,
})

STYLE = {
    "none": ("o-", "#c0392b", "no frame (retracing)"),
    "frameA": ("s-", "#2f6fb0", "Frame A (non-retracing)"),
}


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--csv", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--title", default="")
    a = p.parse_args()

    rows = list(csv.DictReader(open(a.csv)))
    for r in rows:
        r["N"] = int(r["N"])
        r["E_shape"] = float(r["E_shape"])

    schemes = []
    for r in rows:
        if r["scheme"] not in schemes:
            schemes.append(r["scheme"])

    fig, axes = plt.subplots(
        1, len(schemes), figsize=(9.5 * len(schemes), 8.0), sharey=True, squeeze=False
    )
    axes = axes[0]

    allN = sorted({r["N"] for r in rows})
    for ax, scheme in zip(axes, schemes):
        for frame, (mk, col, lab) in STYLE.items():
            sel = sorted(
                [r for r in rows if r["scheme"] == scheme and r["frame"] == frame],
                key=lambda r: r["N"],
            )
            if not sel:
                continue
            ns = np.array([r["N"] for r in sel], dtype=float)
            es = np.array([r["E_shape"] for r in sel])
            ax.loglog(ns, es, mk, color=col, lw=2.6, ms=11, label=lab)
            for i in range(1, len(ns)):
                o = math.log(es[i - 1] / es[i]) / math.log(ns[i] / ns[i - 1])
                ax.annotate(
                    f"{o:.2f}",
                    (math.sqrt(ns[i - 1] * ns[i]),
                     math.sqrt(es[i - 1] * es[i]) * (1.5 if frame == "none" else 0.55)),
                    fontsize=FS - 5, color=col, ha="center",
                )
        base = sorted(
            [r for r in rows if r["scheme"] == scheme and r["frame"] == "none"],
            key=lambda r: r["N"],
        )
        if base:
            nr = np.array([base[0]["N"], base[-1]["N"]], dtype=float)
            ax.loglog(nr, base[0]["E_shape"] * (nr / nr[0]) ** -2.0, "k:", lw=2.0,
                      label="2nd order")
        ax.set_xscale("log", base=2)
        ax.set_xticks(allN)
        ax.set_xticklabels([str(n) for n in allN])
        ax.set_xlabel("$N$ (cells per direction)")
        ax.set_title(scheme)
        ax.grid(True, which="both", alpha=0.25, lw=0.8)
        ax.legend(frameon=False, loc="lower left")

    axes[0].set_ylabel(r"$E_{\mathrm{shape}}(T)$")
    if a.title:
        fig.suptitle(a.title, fontsize=FS + 2)
        fig.tight_layout(rect=[0, 0, 1, 0.93])
    else:
        fig.tight_layout()

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    fig.savefig(a.out, dpi=160)
    print(a.out)


if __name__ == "__main__":
    main()
