#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean

gmsh -0 constant/levitatorWedgeHex.geo
runApplication gmshToFoam  constant/levitatorWedgeHex.msh
rm constant/levitatorWedgeHex.msh
runApplication changeDictionary
restore0Dir
runApplication setAlphaField
runApplication decomposePar

runParallel acousticTDSPMLFoam
#------------------------------------------------------------------------------
