#!/bin/sh

# Single source of truth for WedgeLevitatorDropAlpha setup.
# Values in this file are injected into:
# - constant/transportProperties
# - 0.orig/p
#
# Workflow:
# 1) Edit values here.
# 2) Run ./Allrun (or ./prepareCase to only regenerate inputs).
# ---------------------------------------------------------------------------
# Solver
# ---------------------------------------------------------------------------
# MPI-capable time-domain acoustic solver.
SOLVER=acousticWaveFoam

# ---------------------------------------------------------------------------
# Drive parameters
# ---------------------------------------------------------------------------
# Driven acoustic frequency [Hz].
DRIVE_F=25250
# Piston normal velocity amplitude for transducer gradient BC [m/s].
: "${PISTON_U:=1}"

# ---------------------------------------------------------------------------
# Fluid / acoustic medium properties
# ---------------------------------------------------------------------------
# Gas sound speed used by geometry and wave-number definitions [m/s].
: "${SOUND_SPEED:=343}"
# Liquid density [kg/m^3].
: "${RHOL:=998.3}"
# Gas density [kg/m^3].
: "${RHOG:=1.2}"
# Gas sound speed [m/s].
: "${CG:=343}"
# Liquid sound speed [m/s].
: "${CL:=1480}"

# ---------------------------------------------------------------------------
# PML parameters (rectangle PML)
# ---------------------------------------------------------------------------
# PML thickness [m].
: "${PML_L:=0.008}"
# Directional maximum damping strengths [1/s].
# The wedge uses rectangular PML regions in x and y, but not in z.
: "${SIGMA_MAX:=-500000}"
: "${SIGMA_MAX_X:=${SIGMA_MAX}}"
: "${SIGMA_MAX_Y:=${SIGMA_MAX}}"
: "${SIGMA_MAX_Z:=0}"
# Polynomial profile order (po), typically 2-4.
: "${PO:=3}"
# Rectangle bounds for PML logic in transportProperties.
# Derived automatically in prepareCase:
#   PML_MAX_X = BU + RR
#   PML_MAX_Y = HS + H
#   PML_MIN_Y = -HS
# Keep only fixed limits here.
: "${PML_MAX_Z:=100}"
: "${PML_MIN_X:=-100}"
: "${PML_MIN_Z:=-100}"

# ---------------------------------------------------------------------------
# Geometry / mesh parameters
# ---------------------------------------------------------------------------
# Levitator geometry dimensions [m].
# H: gap between transducer plane and reflector plane.
: "${H:=0.00764}"
# Optional normalized height H/lambda. When set, prepareCase computes:
#   H = HEIGHT_FAC * (SOUND_SPEED/DRIVE_F)
# and centers the drop at H/2.
: "${HEIGHT_FAC:=}"
# RT: transducer radius.
: "${RT:=0.01}"
# RR: reflector radius.
: "${RR:=0.019}"
# BU: radial air buffer beyond reflector radius (outer side extension).
: "${BU:=0.01}"
# HS: vertical stand height above/below the active gap.
: "${HS:=0.01}"

# Wedge total angle [deg].
: "${WEDGE_DEG:=1.0}"

# cfMesh controls [m].
: "${AXIS_RADIUS:=1.0e-5}"
: "${SURFACE_THICKNESS:=0.1}"
: "${CFMESH_MAX_CELL_SIZE:=10e-5}"

# Refine only mixed cells generated by setAlphaField, not a geometric box.
# Adjacent layers grow the selected set on both liquid and gas sides.
# Each refinement level halves selected cells in radial and vertical directions.
: "${ALPHA_INTERFACE_REFINEMENT:=0}"
: "${ALPHA_INTERFACE_REFINEMENT_LEVELS:=1}"
: "${ALPHA_INTERFACE_ADJACENT_LAYERS:=1}"

# ---------------------------------------------------------------------------
# Initial drop setup (setAlphaField)
# ---------------------------------------------------------------------------
# Initial spherical/equivalent drop radius [m].
: "${DROP_RADIUS:=0.001}"
: "${DROP_EQUIV_RADIUS:=${DROP_RADIUS}}"
# Horizontal long semi-axis [m]. Set equal to DROP_RADIUS for a sphere.
: "${DROP_HORIZONTAL_LONG_AXIS:=0.001}"
# Small x/z offsets keep the center away from the wedge singular line.
: "${DROP_CENTER_X:=1e-8}"
# Initial drop center vertical position [m] (y-coordinate).
: "${DROP_CENTER_Y:=0.00382}"
: "${DROP_CENTER_Z:=1e-8}"
