#!/usr/bin/env python3

from os import environ
from pathlib import Path


def value(name):
    return float(environ[name])


def fmt(number):
    return f"{number:.12g}"


case = Path(".")
constant = case / "constant"
system = case / "system"

H = value("H")
RT = value("RT")
RR = value("RR")
BU = value("BU")
HS = value("HS")
WEDGE_DEG = value("WEDGE_DEG")
AXIS_RADIUS = value("AXIS_RADIUS")
SURFACE_THICKNESS = value("SURFACE_THICKNESS")
CFMESH_MAX_CELL_SIZE = value("CFMESH_MAX_CELL_SIZE")

patches = [
    ("transducer1", "wall"),
    ("reflector1", "wall"),
    ("openAir", "wall"),
    ("reflector2", "wall"),
    ("transducer2", "wall"),
    ("axis", "symmetryPlane"),
]
patch_id = {name: index for index, (name, _) in enumerate(patches)}

points2d = [
    (AXIS_RADIUS, 0.0),
    (RT, 0.0),
    (RR, 0.0),
    (RR, -HS),
    (RR + BU, -HS),
    (RR + BU, 0.0),
    (RR + BU, H),
    (RR + BU, H + HS),
    (RR, H + HS),
    (RT, H + HS),
    (RT, H),
    (AXIS_RADIUS, H),
]
# Match the Gmsh physical surfaces for the same wedge geometry.
segment_patches = [
    "reflector1",
    "reflector1",
    "reflector2",
    "openAir",
    "openAir",
    "openAir",
    "openAir",
    "openAir",
    "openAir",
    "transducer2",
    "transducer1",
    "axis",
]

n2 = len(points2d)
points = [(x, y, 0.0) for x, y in points2d]
points.extend((x, y, SURFACE_THICKNESS) for x, y in points2d)

faces = []
for index, patch_name in enumerate(segment_patches):
    next_index = (index + 1) % n2
    patch = patch_id[patch_name]
    faces.append((index, next_index, next_index + n2, patch))
    faces.append((index, next_index + n2, index + n2, patch))

with (constant / "levitator2D.fms").open("w") as output:
    output.write(f"{len(patches)}\n(\n")
    for name, patch_type in patches:
        output.write(f"{name}\n{patch_type}\n\n")
    output.write(")\n\n")
    output.write(f"{len(points)}\n(\n")
    for x, y, z in points:
        output.write(f"({fmt(x)} {fmt(y)} {fmt(z)})\n")
    output.write(")\n\n")
    output.write(f"{len(faces)}\n(\n")
    for a, b, c, patch in faces:
        output.write(f"(({a} {b} {c}) {patch})\n")
    output.write(")\n\n0()\n\n0\n(\n)\n\n0\n(\n)\n\n0\n(\n)\n")

(system / "meshDict").write_text(
    f"""FoamFile
{{
    version   2.0;
    format    ascii;
    class     dictionary;
    location  "system";
    object    meshDict;
}}

// Generated by prepareCase from cfMesh controls in caseParams.sh.
surfaceFile "constant/levitator2D.fms";

maxCellSize {fmt(CFMESH_MAX_CELL_SIZE)};

// ************************************************************************* //
"""
)

(system / "extrudeMeshDict").write_text(
    f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      extrudeMeshDict;
}}

constructFrom patch;
sourceCase    ".";

sourcePatches (bottomEmptyFaces);
exposedPatchName topEmptyFaces;

extrudeModel wedge;

sectorCoeffs
{{
    point       (0 0 0);
    axis        (0 -1 0);
    angle       {fmt(WEDGE_DEG)};
}}

flipNormals true;
mergeFaces false;

// ************************************************************************* //
"""
)
