#!/bin/sh
set -eu

cd "${0%/*}" || exit 1
. ./caseParams.sh

if [ -n "${HEIGHT_FAC}" ]; then
    WAVELENGTH="$(awk -v c="$SOUND_SPEED" -v f="$DRIVE_F" 'BEGIN{printf "%.12g", c/f}')"
    H="$(awk -v fac="$HEIGHT_FAC" -v lam="$WAVELENGTH" 'BEGIN{printf "%.12g", fac*lam}')"
    DROP_CENTER_Y="$(awk -v d="$H" 'BEGIN{printf "%.12g", 0.5*d}')"
fi

# Derived rectangular PML bounds from geometry parameters.
PML_MAX_X="$(awk -v bu="$BU" -v rr="$RR" 'BEGIN{printf "%.12g", bu + rr}')"
PML_MAX_Y="$(awk -v hs="$HS" -v d="$H" 'BEGIN{printf "%.12g", hs + d}')"
PML_MIN_Y="$(awk -v hs="$HS" 'BEGIN{printf "%.12g", -hs}')"

render()
{
    inFile="$1"
    outFile="$2"

    sed \
        -e "s|__DRIVE_F__|$DRIVE_F|g" \
        -e "s|__PISTON_U__|$PISTON_U|g" \
        -e "s|__SOUND_SPEED__|$SOUND_SPEED|g" \
        -e "s|__RHOL__|$RHOL|g" \
        -e "s|__RHOG__|$RHOG|g" \
        -e "s|__CG__|$CG|g" \
        -e "s|__CL__|$CL|g" \
        -e "s|__PML_L__|$PML_L|g" \
        -e "s|__SIGMA_MAX__|$SIGMA_MAX|g" \
        -e "s|__SIGMA_MAX_X__|$SIGMA_MAX_X|g" \
        -e "s|__SIGMA_MAX_Y__|$SIGMA_MAX_Y|g" \
        -e "s|__SIGMA_MAX_Z__|$SIGMA_MAX_Z|g" \
        -e "s|__PO__|$PO|g" \
        -e "s|__PML_MAX_X__|$PML_MAX_X|g" \
        -e "s|__PML_MAX_Y__|$PML_MAX_Y|g" \
        -e "s|__PML_MAX_Z__|$PML_MAX_Z|g" \
        -e "s|__PML_MIN_X__|$PML_MIN_X|g" \
        -e "s|__PML_MIN_Y__|$PML_MIN_Y|g" \
        -e "s|__PML_MIN_Z__|$PML_MIN_Z|g" \
        -e "s|__H__|$H|g" \
        -e "s|__RT__|$RT|g" \
        -e "s|__RR__|$RR|g" \
        -e "s|__BU__|$BU|g" \
        -e "s|__HS__|$HS|g" \
        -e "s|__WEDGE_DEG__|$WEDGE_DEG|g" \
        -e "s|__DROP_RADIUS__|$DROP_RADIUS|g" \
        -e "s|__DROP_HORIZONTAL_LONG_AXIS__|$DROP_HORIZONTAL_LONG_AXIS|g" \
        -e "s|__DROP_CENTER_X__|$DROP_CENTER_X|g" \
        -e "s|__DROP_CENTER_Y__|$DROP_CENTER_Y|g" \
        -e "s|__DROP_CENTER_Z__|$DROP_CENTER_Z|g" \
        -e "s|__ALPHA_INTERFACE_ADJACENT_LAYERS__|$ALPHA_INTERFACE_ADJACENT_LAYERS|g" \
        "$inFile" > "$outFile"
}

render constant/transportProperties.in constant/transportProperties
render 0.orig/p.in 0.orig/p
render system/setAlphaFieldDict.in system/setAlphaFieldDict

export H RT RR BU HS WEDGE_DEG AXIS_RADIUS SURFACE_THICKNESS
export CFMESH_MAX_CELL_SIZE

python3 ./generateCfMeshInputs.py

render system/topoSetDict.alphaInterface.in system/topoSetDict.alphaInterface
