#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

set -e
cd "${0%/*}" || exit 1
rm -rf 0
cp -r 0.orig 0
rm -rf constant/polyMesh
rm -rf [1-9]* [0-9]*.[0-9]*
rm -rf postProcessing VTK
rm -f log.* studyProperties
