#!/bin/sh
set -e
cd "${0%/*}" || exit 1
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
. ./caseParams.sh

./Allclean
./prepareCase
restore0Dir
rm -f 0/*.in

runApplication blockMesh
runApplication setAlphaField
runApplication setPMLFields
runApplication decomposePar -force
runParallel "${SOLVER}"
runApplication reconstructPar -latestTime

python3 postprocess_interface.py
