#!/bin/sh
set -eu

cd "${0%/*}" || exit 1
. ./caseParams.sh

# Derived wavelength and geometric height.
WAVELENGTH="$(awk -v c="$SOUND_SPEED" -v f="$DRIVE_F" 'BEGIN{printf "%.12g", c/f}')"
D="$(awk -v fac="$HEIGHT_FAC" -v lam="$WAVELENGTH" 'BEGIN{printf "%.12g", fac*lam}')"
DROP_CENTER_Y="$(awk -v d="$D" 'BEGIN{printf "%.12g", 0.5*d}')"

case "${DROP_MODE}" in
    empty)
        EFFECTIVE_DROP_ASPECT_RATIO=1.0
        ;;
    oblate)
        if ! awk -v ar="$DROP_ASPECT_RATIO" 'BEGIN{exit !(ar > 0)}'; then
            echo "DROP_ASPECT_RATIO must be > 0 for DROP_MODE=oblate" >&2
            exit 1
        fi
        EFFECTIVE_DROP_ASPECT_RATIO="$DROP_ASPECT_RATIO"
        ;;
    *)
        echo "Unsupported DROP_MODE='${DROP_MODE}'. Use 'empty' or 'oblate'." >&2
        exit 1
        ;;
esac

# Constant-volume spheroid:
#   a^2 * b = R^3 with aspect ratio a/b.
DROP_AXIS_X="$(awk -v r="$DROP_EQUIV_RADIUS" -v ar="$EFFECTIVE_DROP_ASPECT_RATIO" 'BEGIN{printf "%.12g", r*exp(log(ar)/3.0)}')"
DROP_AXIS_Y="$(awk -v r="$DROP_EQUIV_RADIUS" -v ar="$EFFECTIVE_DROP_ASPECT_RATIO" 'BEGIN{printf "%.12g", r*exp((-2.0/3.0)*log(ar))}')"
DROP_AXIS_Z="$DROP_AXIS_X"

# Derived rectangular PML bounds from geometry parameters.
PML_MAX_X="$(awk -v bu="$BU" -v rr="$RR" 'BEGIN{printf "%.12g", bu + rr}')"
PML_MAX_Y="$(awk -v hs="$HS" -v d="$D" 'BEGIN{printf "%.12g", hs + d}')"
PML_MIN_Y="$(awk -v hs="$HS" 'BEGIN{printf "%.12g", -hs}')"

render()
{
    inFile="$1"
    outFile="$2"

    sed \
        -e "s|__DRIVE_F__|$DRIVE_F|g" \
        -e "s|__PISTON_U__|$PISTON_U|g" \
        -e "s|__SOUND_SPEED__|$SOUND_SPEED|g" \
        -e "s|__RHOL__|$RHOL|g" \
        -e "s|__RHOG__|$RHOG|g" \
        -e "s|__CG__|$CG|g" \
        -e "s|__CL__|$CL|g" \
        -e "s|__PML_L__|$PML_L|g" \
        -e "s|__SIGMA_MAX__|$SIGMA_MAX|g" \
        -e "s|__PO__|$PO|g" \
        -e "s|__PML_MAX_X__|$PML_MAX_X|g" \
        -e "s|__PML_MAX_Y__|$PML_MAX_Y|g" \
        -e "s|__PML_MAX_Z__|$PML_MAX_Z|g" \
        -e "s|__PML_MIN_X__|$PML_MIN_X|g" \
        -e "s|__PML_MIN_Y__|$PML_MIN_Y|g" \
        -e "s|__PML_MIN_Z__|$PML_MIN_Z|g" \
        -e "s|__D__|$D|g" \
        -e "s|__RT__|$RT|g" \
        -e "s|__RR__|$RR|g" \
        -e "s|__BU__|$BU|g" \
        -e "s|__HS__|$HS|g" \
        -e "s|__MESH_N__|$MESH_N|g" \
        -e "s|__MESH_LC__|$MESH_LC|g" \
        -e "s|__ROTATE_HALF_DEG__|$ROTATE_HALF_DEG|g" \
        -e "s|__WEDGE_DEG__|$WEDGE_DEG|g" \
        -e "s|__DROP_CENTER_X__|$DROP_CENTER_X|g" \
        -e "s|__DROP_CENTER_Y__|$DROP_CENTER_Y|g" \
        -e "s|__DROP_CENTER_Z__|$DROP_CENTER_Z|g" \
        -e "s|__DROP_AXIS_X__|$DROP_AXIS_X|g" \
        -e "s|__DROP_AXIS_Y__|$DROP_AXIS_Y|g" \
        -e "s|__DROP_AXIS_Z__|$DROP_AXIS_Z|g" \
        "$inFile" > "$outFile"
}

render constant/transportProperties.in constant/transportProperties
render constant/levitatorWedgeHex.geo.in constant/levitatorWedgeHex.geo
render 0.orig/Pim.in 0.orig/Pim
render system/setExprFieldsDict.in system/setExprFieldsDict
