#!/bin/sh
set -e
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ./caseParams.sh                                   # Case parameters
#------------------------------------------------------------------------------

case "${MESHER:-gmsh}" in
    gmsh|cfmesh)
        ;;
    *)
        echo "Error: unsupported MESHER='${MESHER}'. Use 'gmsh' or 'cfmesh'." >&2
        exit 1
        ;;
esac

./Allclean
./prepareCase

case "${MESHER:-gmsh}" in
    gmsh)
        restore0Dir
        gmsh -0 constant/levitatorWedgeHex.geo
        runApplication gmshToFoam  constant/levitatorWedgeHex.msh
        rm constant/levitatorWedgeHex.msh
        runApplication changeDictionary
        ;;
    cfmesh)
        runApplication cartesian2DMesh
        runApplication extrudeMesh
        ./postMesh
        restore0Dir
        ;;
esac

runApplication setAlphaField
rm -f 0/Pim.in

runApplication setPMLFields

rm -f "log.${SOLVER}"
runApplication decomposePar -force
runParallel "${SOLVER}"
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
