#!/bin/sh
set -eu

cd "${0%/*}" || exit 1
. ./caseParams.sh

render()
{
    inFile="$1"
    outFile="$2"

    sed \
        -e "s|__DRIVE_F__|$DRIVE_F|g" \
        -e "s|__PISTON_U__|$PISTON_U|g" \
        -e "s|__RHOL__|$RHOL|g" \
        -e "s|__RHOG__|$RHOG|g" \
        -e "s|__CG__|$CG|g" \
        -e "s|__CL__|$CL|g" \
        -e "s|__SIGMA_MAX__|$SIGMA_MAX|g" \
        -e "s|__PO__|$PO|g" \
        -e "s|__SHIFTED_LAPLACIAN_BETA__|$SHIFTED_LAPLACIAN_BETA|g" \
        -e "s|__PML_RMIN__|$PML_RMIN|g" \
        -e "s|__PML_RMAX__|$PML_RMAX|g" \
        -e "s|__MESH_CELLS_PER_LAMBDA__|$MESH_CELLS_PER_LAMBDA|g" \
        -e "s|__MESH_GR__|$MESH_GR|g" \
        -e "s|__WEDGE_ANGLE_DEG__|$WEDGE_ANGLE_DEG|g" \
        "$inFile" > "$outFile"
}

render constant/transportProperties.in constant/transportProperties
render constant/pistonRadiation.geo.in constant/pistonRadiation.geo
render templates/Pim.in 0.orig/Pim
