#!/bin/sh
set -e
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ./caseParams.sh                                   # Case parameters
#------------------------------------------------------------------------------

SOLVER=acousticDropEquilibriumFoam

./Allclean
./prepareCase

runApplication cartesian2DMesh
runApplication extrudeMesh
./postMesh
restore0Dir
rm -f 0/Pim.in

runApplication setPMLFields

rm -f "log.${SOLVER}"
runApplication decomposePar -force
runParallel "${SOLVER}"

#------------------------------------------------------------------------------
