#!/bin/sh
set -eu

cd "${0%/*}" || exit 1

boundaryFile="constant/polyMesh/boundary"

perl -0pi -e '
    s/\bbottomEmptyFaces\b/front/g;
    s/\btopEmptyFaces\b/back/g;
' "$boundaryFile"

perl -0pi -e '
    s/(transducer1\s*\{[^}]*?\btype\s*)wall;/${1}patch;/s;
    s/(transducer1\s*\{[^}]*?\binGroups\s*)1\(wall\);/${1}1(patch);/s;
    s/(reflector1\s*\{[^}]*?\btype\s*)wall;/${1}patch;/s;
    s/(reflector1\s*\{[^}]*?\binGroups\s*)1\(wall\);/${1}1(patch);/s;
    s/(openAir\s*\{[^}]*?\btype\s*)wall;/${1}patch;/s;
    s/(openAir\s*\{[^}]*?\binGroups\s*)1\(wall\);/${1}1(patch);/s;
    s/(reflector2\s*\{[^}]*?\btype\s*)wall;/${1}patch;/s;
    s/(reflector2\s*\{[^}]*?\binGroups\s*)1\(wall\);/${1}1(patch);/s;
    s/(transducer2\s*\{[^}]*?\btype\s*)wall;/${1}patch;/s;
    s/(transducer2\s*\{[^}]*?\binGroups\s*)1\(wall\);/${1}1(patch);/s;
    s/(dropWall\s*\{[^}]*?\btype\s*)wall;/${1}patch;/s;
    s/(dropWall\s*\{[^}]*?\binGroups\s*)1\(wall\);/${1}1(patch);/s;
' "$boundaryFile"
