#!/bin/sh
set -e
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ./caseParams.sh                                   # Case parameters
#------------------------------------------------------------------------------

SOLVER=acousticHelmholtzFoam

./Allclean
./prepareCase

restore0Dir
gmsh -0 constant/levitatorWedgeHex.geo
runApplication gmshToFoam constant/levitatorWedgeHex.msh
rm -f constant/levitatorWedgeHex.msh
runApplication changeDictionary
rm -f 0/Pim.in

runApplication setPMLFields

rm -f "log.${SOLVER}"
if [ "${solverMode}" = "parallel" ]; then
    runApplication decomposePar -force
    runParallel "${SOLVER}"
    runApplication reconstructPar -latestTime
else
    runApplication "${SOLVER}"
fi

#------------------------------------------------------------------------------
