#!/bin/sh
set -e
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ./caseParams.sh                                   # Case parameters
#------------------------------------------------------------------------------

need_cmd()
{
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Error: required command '$1' not found in PATH" >&2
        exit 1
    fi
}

need_cmd gmsh

SOLVER=acousticHelmholtzFoam

if [ "${solverMode}" = "parallel" ]; then
    if [ -z "${NPROCS:-}" ]; then
        NPROCS="$(awk '/^[[:space:]]*numberOfSubdomains[[:space:]]+/ {gsub(/;/, "", $2); print $2; exit}' system/decomposeParDict)"
    fi
    : "${NPROCS:=4}"
fi

./Allclean
./prepareCase

restore0Dir
gmsh -0 constant/levitatorWedgeHex.geo
runApplication gmshToFoam constant/levitatorWedgeHex.msh
rm -f constant/levitatorWedgeHex.msh
runApplication changeDictionary
rm -f 0/Pim.in

need_cmd setPMLFields
runApplication setPMLFields

need_cmd "${SOLVER}"
rm -f "log.${SOLVER}"
if [ "${solverMode}" = "parallel" ]; then
    runApplication decomposePar -force
    runParallel "${SOLVER}"
    runApplication reconstructPar -latestTime
else
    runApplication "${SOLVER}"
fi

#------------------------------------------------------------------------------
