#!/bin/sh
set -eu

cd "${0%/*}" || exit 1
. ./caseParams.sh

PML_MAX_X="$(awk -v bu="$BU" -v rr="$RR" 'BEGIN{printf "%.12g", bu + rr}')"
PML_MAX_Y="$(awk -v hs="$HS" -v d="$D" 'BEGIN{printf "%.12g", hs + d}')"
PML_MIN_Y="$(awk -v hs="$HS" 'BEGIN{printf "%.12g", -hs}')"

render()
{
    inFile="$1"
    outFile="$2"

    sed \
        -e "s|__DRIVE_F__|$DRIVE_F|g" \
        -e "s|__PISTON_U__|$PISTON_U|g" \
        -e "s|__SOUND_SPEED__|$SOUND_SPEED|g" \
        -e "s|__RHOL__|$RHOL|g" \
        -e "s|__RHOG__|$RHOG|g" \
        -e "s|__CG__|$CG|g" \
        -e "s|__CL__|$CL|g" \
        -e "s|__PML_L__|$PML_L|g" \
        -e "s|__SIGMA_MAX__|$SIGMA_MAX|g" \
        -e "s|__PO__|$PO|g" \
        -e "s|__PML_MAX_X__|$PML_MAX_X|g" \
        -e "s|__PML_MAX_Y__|$PML_MAX_Y|g" \
        -e "s|__PML_MAX_Z__|$PML_MAX_Z|g" \
        -e "s|__PML_MIN_X__|$PML_MIN_X|g" \
        -e "s|__PML_MIN_Y__|$PML_MIN_Y|g" \
        -e "s|__PML_MIN_Z__|$PML_MIN_Z|g" \
        -e "s|__AXIS_RADIUS__|$AXIS_RADIUS|g" \
        -e "s|__D__|$D|g" \
        -e "s|__RT__|$RT|g" \
        -e "s|__RR__|$RR|g" \
        -e "s|__BU__|$BU|g" \
        -e "s|__HS__|$HS|g" \
        -e "s|__WEDGE_DEG__|$WEDGE_DEG|g" \
        -e "s|__DROP_RADIUS__|$DROP_RADIUS|g" \
        -e "s|__DROP_CENTER_Y__|$DROP_CENTER_Y|g" \
        "$inFile" > "$outFile"
}

render constant/transportProperties.in constant/transportProperties
render 0.orig/Pim.in 0.orig/Pim
render system/setAlphaFieldDict.in system/setAlphaFieldDict
render system/extrudeMeshDict.in system/extrudeMeshDict

RRBU="$(awk -v rr="$RR" -v bu="$BU" 'BEGIN{printf "%.12g", rr + bu}')"
DPHS="$(awk -v d="$D" -v hs="$HS" 'BEGIN{printf "%.12g", d + hs}')"

INTERFACE_REFS="$(
awk -v ax="$AXIS_RADIUS" \
    -v cy="$DROP_CENTER_Y" \
    -v r="$DROP_RADIUS" \
    -v z="$SURFACE_THICKNESS" \
    -v n="$CFMESH_INTERFACE_SEGMENTS" \
    -v cs="$CFMESH_DROP_CELL_SIZE" '
BEGIN {
    pi = atan2(0, -1);
    for (i = 0; i < n; ++i)
    {
        t0 = i*pi/n;
        t1 = (i+1)*pi/n;
        x0 = ax + r*sin(t0);
        y0 = cy + r*cos(t0);
        x1 = ax + r*sin(t1);
        y1 = cy + r*cos(t1);

        printf("    interfaceSeg%02d\n", i+1);
        printf("    {\n");
        printf("        type        line;\n");
        printf("        cellSize    %.12g;\n", cs);
        printf("        p0          (%.12g %.12g %.12g);\n", x0, y0, 0.5*z);
        printf("        p1          (%.12g %.12g %.12g);\n", x1, y1, 0.5*z);
        printf("    }\n");
    }
}')"

cat > system/meshDict <<EOF
/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                |
| \\\\      /  F ield         | cfMesh: A library for mesh generation          |
|  \\\\    /   O peration     |                                                |
|   \\\\  /    A nd           | Author: Franjo Juretic                         |
|    \\\\/     M anipulation  | E-mail: franjo.juretic@c-fields.com            |
\\*---------------------------------------------------------------------------*/

FoamFile
{
    version   2.0;
    format    ascii;
    class     dictionary;
    location  "system";
    object    meshDict;
}

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

surfaceFile "constant/levitator2D.fms";

maxCellSize $CFMESH_MAX_CELL_SIZE;

objectRefinements
{
$INTERFACE_REFS
}

// ************************************************************************* //
EOF

cat > constant/levitator2D.fms <<EOF
6
(
transducer1
wall

reflector1
wall

openAir
wall

reflector2
wall

transducer2
wall

axis
symmetryPlane

)

24
(
($AXIS_RADIUS 0 0)
($RT 0 0)
($RR 0 0)
($RR -$HS 0)
($RRBU -$HS 0)
($RRBU 0 0)
($RRBU $D 0)
($RRBU $DPHS 0)
($RR $DPHS 0)
($RT $DPHS 0)
($RT $D 0)
($AXIS_RADIUS $D 0)

($AXIS_RADIUS 0 $SURFACE_THICKNESS)
($RT 0 $SURFACE_THICKNESS)
($RR 0 $SURFACE_THICKNESS)
($RR -$HS $SURFACE_THICKNESS)
($RRBU -$HS $SURFACE_THICKNESS)
($RRBU 0 $SURFACE_THICKNESS)
($RRBU $D $SURFACE_THICKNESS)
($RRBU $DPHS $SURFACE_THICKNESS)
($RR $DPHS $SURFACE_THICKNESS)
($RT $DPHS $SURFACE_THICKNESS)
($RT $D $SURFACE_THICKNESS)
($AXIS_RADIUS $D $SURFACE_THICKNESS)
)

24
(
((0 1 13) 1)
((0 13 12) 1)

((1 2 14) 1)
((1 14 13) 1)
((2 3 15) 3)
((2 15 14) 3)

((3 4 16) 2)
((3 16 15) 2)
((4 5 17) 2)
((4 17 16) 2)
((5 6 18) 2)
((5 18 17) 2)
((6 7 19) 2)
((6 19 18) 2)
((7 8 20) 2)
((7 20 19) 2)
((8 9 21) 2)
((8 21 20) 2)

((9 10 22) 4)
((9 22 21) 4)

((10 11 23) 0)
((10 23 22) 0)

((11 0 12) 5)
((11 12 23) 5)
)

0()

0
(
)

0
(
)

0
(
)
EOF
