#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./clean

restore0Dir

runApplication blockMesh

runApplication setAlphaField

# runApplication decomposePar -cellDist
# runParallel interIsoModiFoam
rm *.dat
runApplication interFlow #interIsoRhoFoam -tScheme Euler #interFlow #interIsoFoam #interFlow #interIsoRhoFoam -tScheme Euler #interFlow
foamSequenceVTKFiles -vtp
touch foam.foam
# $(getApplication)

#------------------------------------------------------------------------------
